FROM mcr.microsoft.com/dotnet/sdk:9.0
WORKDIR /app
COPY . ./

# Restore as distinct layers
RUN dotnet restore src/CartonCaps.csproj

CMD ["dotnet", "watch", "run", "--project", "src/CartonCaps.csproj", "--urls", "http://0.0.0.0:8080"]